version : '2'
services :

# yourweb5.com
  php53:
    container_name: 4php53-fpm
    build: ./php5 
    working_dir: "/var/www"
    volumes:
        - ./www/www5:/var/www
        - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
        - ./php/pool.conf:/usr/local/etc/php/pool.conf:ro
    expose:
      - "9000"

# yourweb.com
  php71:
    container_name: 4php71-fpm
    build: ./php7 
    restart: always
    volumes:
      - ./www/www7:/var/www
    expose:
      - "9000"

  nginx:
    container_name: 4nginx
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./www:/var/www
    ports:
      - 80:80

  mysql:
    container_name: 4mysql
    image: mysql:5.6
    environment:
        MYSQL_ROOT_PASSWORD: rootdocker
    ports:
      - 3306:3306
      
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: 4myadmin
    restart: always
    environment:
        PMA_HOST : mysql
    ports:
      - "8000:80"

